name: 🤖 CI/CD
description: Open new enhancement issue regarding CI/CD improvement
title: "[FEATURE]: "
labels: ["🌟 [A] enhancement"]
body:

- type: markdown
  attributes:
    value: |
      ![Static Badge](https://img.shields.io/badge/issue-%E2%9E%95_feature_general-black?logo=github&color=%230096FF%09&cacheSeconds=0)
      
      Please, fill out this form to submit a new `Feature Request` for the Betarena - Scores Platform.

- type: checkboxes
  attributes:
    label: Does a duplicate issue exist?
    description: |
      Please search to see if an issue already exists for the feature you are requesting. 
    options:
    - label: I have searched the existing issues
      required: true

- type: textarea
  attributes:
    label: 🤔 Is request related to a problem? Please describe the problem.
    description: |
      A clear and concise description of what the problem is. 
    placeholder: |
      Example:
      - I am trying to do [...] but [...]
      - This is not working, due to external factors, and needs to be fixed by adding <example>.
  validations:
    required: false

- type: textarea
  attributes:
    label: 📝 Issue Request Description
    description: |
      A clear and concise description of what you want to happen. Include any alternative solutions you've considered.
  validations:
    required: true

- type: textarea
  attributes:
    label: ➕ Context and resources (cummulative)
    description: |
      Add any other `context`, `screenshots` or `resources` about the `feature request` goes here.
    placeholder: |
      ---
      [dd/MM/yyyy]
      - New resource found: <link>.
      - New solution alternative example.
  validations:
    required: false
