name: ⚡ SCORES-LIB | Feature Request Internal 
description: New Feature Request (Scores-Lib) by Internal Betarena Team
title: "[FEATURE-I-ScL]: "
labels: ["🌟 [A] enhancement"]
projects: ["Betarena Scores"]
body:

- type: markdown
  attributes:
    value: |
      ![Static Badge](https://img.shields.io/badge/issue-%E2%9A%A1%EF%B8%8F_feature_internal-black?logo=github&color=%2300FFFF&cacheSeconds=0)
      
      Please, fill out this form to submit a new `Feature Request` of type `Widget` for the Betarena - Scores Platform as an Internal Betarena Team member.

- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: |
      Please search to see if an issue already exists for the feature you are requesting. ([scores/issues](https://github.com/Betarena/scores/issues)).
    options:
    - label: I have searched the existing issues
      required: true

- type: checkboxes
  attributes:
    label: Is this issue created as a result of another issue ? (i.e. offspring)
    description: |
      Has this issue originated from another issue, that requires tackling of another project ?
    options:
    - label: Yes, its an offspring
      required: false

- type: textarea
  attributes:
    label: 📝 Description
    description: |
      NOTE: If the issue is created as a result of an 'offspring', please reference the original parent issue.
  validations:
    required: true

- type: textarea
  attributes:
    label: ❓ Anything else? Additional remarks?
    description: |
      You can include here `information`, such as:
      - Target Feature Geo Location.
      - Figma design links.
      - Additional references.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
